[package]
name = "rusty_brot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorgrad = "0.6.2"
image = "0.24.6"
rayon = "1.7.0"
